### PR TITLE
Compile with -fPIC

### PR DESCRIPTION
**Pull request by eWert-Online**

### CODE REVIEW

**Comment by EduardoRFS** [comment]
Thank you so much, will look on this today or tomorrow

**Comment by eWert-Online** [comment]
Do you know, if there is a specific reason, why `-O2` was not enabled?
Having this enabled, results in [odiff](https://github.com/dmtrKovalenko/odiff) being  around 2.5 times faster than without.

**Comment by eWert-Online** [comment]
@ManasJayanth, @EduardoRFS 
Did you find some time to look at this yet? 🙂

**Comment by ManasJayanth** [comment]
Sorry, fell off the radar. Trying it in the evening.

**Comment by ManasJayanth** [comment]
@EduardoRFS Can't remember correctly, but packages compiled with fpic are incompatible with static linking, no?

If so, we'll need a more convenient way for users to support variants of packages like this. Another example, AFL enabled OCaml compiler.

**Comment by EduardoRFS** [comment]
@ManasJayanth no they're not

**Review by EduardoRFS — APPROVED** [review]
Seems reasonable to me

**Comment by ManasJayanth** [comment]
> Can't remember correctly, but packages compiled with fpic are incompatible with static linking, no?

This was fpie not fPIC.

Merging. Thank you @eWert-Online

**Pull request merged**
